# Generated by Django 6.0.4 on 2026-04-08 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_intro'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_bg_image',
            field=models.ForeignKey(blank=True, help_text='Background image / video poster', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_bg_video_url',
            field=models.CharField(blank=True, default='vids/hero-rgp.mp4', help_text='Path relative to public/ folder, or a full https:// URL', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_label',
            field=models.CharField(default='Explore Properties', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='350+ premium properties delivered — luxury villas, penthouses & exclusive estates crafted for those who demand the extraordinary.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_line1',
            field=models.CharField(default='Your Dream Home', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_line1_highlight',
            field=models.CharField(blank=True, default='Dream', help_text='Word in line 1 to render in gold', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_line2',
            field=models.CharField(default='Perfectly Delivered', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_line2_highlight',
            field=models.CharField(blank=True, default='Perfectly', help_text='Word in line 2 to render in amber', max_length=50),
        ),
    ]
