# Generated by Django 6.0.4 on 2026-04-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_intro_homepage_hero_bg_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_btn1_label',
            field=models.CharField(default='Buy', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn1_url',
            field=models.CharField(default='/properties?cat=for-sale', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn2_label',
            field=models.CharField(default='Rent', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn2_url',
            field=models.CharField(default='/properties?cat=for-rent', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn3_label',
            field=models.CharField(default='Sold', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn3_url',
            field=models.CharField(default='/properties?cat=sold', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn4_label',
            field=models.CharField(default='Agent', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_btn4_url',
            field=models.CharField(default='/team', max_length=255),
        ),
    ]
