# Generated by Django 6.0.4 on 2026-04-08 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_btn1_label_homepage_hero_btn1_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_label',
        ),
    ]
