# Generated by Django 6.0.4 on 2026-04-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_hero_cta_label'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro_cta1_label',
            field=models.CharField(default='Book a Free Appraisal', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_cta1_url',
            field=models.CharField(default='/contact', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_cta2_label',
            field=models.CharField(default='Meet Rahul', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_cta2_url',
            field=models.CharField(default='/about', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_founder_name',
            field=models.CharField(default='— Rahul Singh', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_headline1',
            field=models.CharField(default='Building Wealth', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_headline2',
            field=models.CharField(default='Through Property,', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_image',
            field=models.ForeignKey(blank=True, help_text='Founder / intro portrait', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_label',
            field=models.CharField(default='About the Founder', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro_text',
            field=models.TextField(default='Real Gold Properties is a vision turned reality — a private equity approach to multi-family real estate. Founded by Rahul Singh, we focus on disciplined acquisitions that deliver consistent returns.'),
        ),
    ]
