# Generated by Django 6.0.4 on 2026-04-08 09:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_intro_cta1_label_homepage_intro_cta1_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='hero_bg_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_bg_video_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_btn1_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_btn1_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_btn2_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_btn2_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_btn3_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_btn3_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_btn4_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_btn4_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_line1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_line1_highlight',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_line2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title_line2_highlight',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_cta1_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_cta1_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_cta2_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_cta2_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_founder_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_headline1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_headline2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 17), ('intro', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Word in line 1 to render in gold', 'max_length': 50, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Word in line 2 to render in amber', 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.TextBlock', (), {'required': False}), 5: ('home.blocks.ImageChooserBlock', (), {'label': 'Background image / poster', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Local path (vids/hero.mp4) or Vimeo URL', 'max_length': 255, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 8: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 9: ('wagtail.blocks.StructBlock', [[('label', 7), ('url', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 30}), 11: ('wagtail.blocks.StructBlock', [[('label', 10), ('url', 8)]], {'label': 'Button 1'}), 12: ('wagtail.blocks.StructBlock', [[('label', 10), ('url', 8)]], {'label': 'Button 2'}), 13: ('wagtail.blocks.StructBlock', [[('label', 10), ('url', 8)]], {'label': 'Button 3'}), 14: ('wagtail.blocks.StructBlock', [[('label', 10), ('url', 8)]], {'label': 'Button 4'}), 15: ('wagtail.blocks.StructBlock', [[('btn1', 11), ('btn2', 12), ('btn3', 13), ('btn4', 14)]], {}), 16: ('wagtail.blocks.StreamBlock', [[('single_cta', 9), ('panel_buttons', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('title_line1', 0), ('title_line1_highlight', 1), ('title_line2', 2), ('title_line2_highlight', 3), ('subtitle', 4), ('bg_image', 5), ('bg_video_url', 6), ('cta', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'About the Founder', 'max_length': 100}), 19: ('wagtail.blocks.TextBlock', (), {}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 21: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': False}), 22: ('home.blocks.ImageChooserBlock', (), {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('label', 18), ('headline1', 0), ('headline2', 2), ('founder_name', 2), ('text', 19), ('cta1_label', 7), ('cta1_url', 8), ('cta2_label', 20), ('cta2_url', 21), ('image', 22)]], {})}),
        ),
    ]
