# Generated by Django 6.0.4 on 2026-04-08 09:39

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('for-sale', 'For Sale'), ('sold', 'Sold'), ('for-rent', 'For Rent')], default='for-sale', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0, help_text='0 = Contact Agent')),
                ('sold_price', models.PositiveIntegerField(blank=True, null=True)),
                ('beds', models.PositiveSmallIntegerField(default=0)),
                ('baths', models.PositiveSmallIntegerField(default=0)),
                ('sqft', models.PositiveIntegerField(default=0)),
                ('garage', models.PositiveSmallIntegerField(default=0)),
                ('badge', models.CharField(blank=True, max_length=60)),
                ('is_new', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('sold_date', models.CharField(blank=True, max_length=60)),
                ('days_on_market', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deposit', models.PositiveIntegerField(blank=True, null=True)),
                ('min_lease', models.CharField(blank=True, max_length=60)),
                ('card_features', models.CharField(blank=True, help_text='Comma-separated e.g. Pool, Solar Panels, Double Garage', max_length=500)),
                ('has_detail_page', models.BooleanField(default=False, help_text='Enable the full detail view')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Sold', 'Sold'), ('Pending', 'Pending')], max_length=20)),
                ('price_label', models.CharField(blank=True, max_length=60)),
                ('featured', models.BooleanField(default=False)),
                ('overview', wagtail.fields.RichTextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True)),
                ('video_tour_url', models.URLField(blank=True)),
                ('agent_name', models.CharField(blank=True, max_length=100)),
                ('agent_title', models.CharField(blank=True, max_length=100)),
                ('agent_phone', models.CharField(blank=True, max_length=30)),
                ('agent_email', models.EmailField(blank=True, max_length=254)),
                ('agent_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('agent_review_count', models.PositiveSmallIntegerField(default=0)),
                ('agent_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('video_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ListingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_rows', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(choices=[('smart-home', 'Smart Home'), ('kitchen', 'Kitchen'), ('ocean', 'Ocean'), ('wine', 'Wine Cellar'), ('pool', 'Pool'), ('dock', 'Dock'), ('theater', 'Theater'), ('gym', 'Gym'), ('security', 'Security'), ('garden', 'Garden'), ('spa', 'Spa'), ('garage', 'Garage')], default='smart-home', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_features', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingNearby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('shopping', 'Shopping'), ('airport', 'Airport'), ('dining', 'Dining'), ('golf', 'Golf'), ('beach', 'Beach'), ('school', 'School'), ('hospital', 'Hospital')], default='shopping', max_length=20)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_locations', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(choices=[('bed', 'Bed'), ('bath', 'Bath'), ('area', 'Area'), ('garage', 'Garage'), ('year', 'Year'), ('lot', 'Lot')], default='bed', max_length=20)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_stats', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
